sudo: required
dist: trusty
language: node_js
node_js:
  - '5.7'

branches:
  only:
  - master

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - export TZ=MST7MDT
  - sh -e /etc/init.d/xvfb start

install:
- npm install -g angular-cli
- npm install -g firebase-tools
- npm install

script:
- ng test -cc -l -sr
- ng build --prod --aot

after_success:
- ./node_modules/.bin/codecov
- firebase use default
- firebase deploy --token ${FIREBASE_TOKEN}
- ./data/seedData ${FIREBASE_TOKEN}
